# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('dr', 'Dr'), ('prof', 'Prof')], max_length=1)),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('farm', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('gram', 'Gram'), ('liter', 'Liter'), ('item', 'Item')], max_length=10)),
                ('grade', models.CharField(choices=[('1', 'Bad'), ('2', 'Somewhat good'), ('3', 'good'), ('4', 'very good'), ('5', 'Top quality')], max_length=1)),
                ('available', models.BooleanField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farmer')),
            ],
        ),
    ]
