# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('d', 'Dairy'), ('f', 'Fruits'), ('v', 'Vegetables'), ('g', 'Grains'), ('o', 'other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='discribe your product eg. my apples are red'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='enter the name of your product eg apples', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('gram', 'Kg'), ('liter', 'liter'), ('item', 'Item')], max_length=10),
        ),
    ]
