# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20170513_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('d', 'Dairy'), ('f', 'Fruits'), ('v', 'Vegetables'), ('g', 'Grains'), ('o', 'other')], max_length=1),
        ),
    ]
