# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_auto_20170513_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
