# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('d', 'Dairy'), ('f', 'Fruits'), ('v', 'Vegetables'), ('g', 'Grains'), ('o', 'other')], max_length=10, null=True),
        ),
    ]
